### ISSUE TITLE
NPE Error (MC1.16.5)

### ISSUE THREAD

**Issue by joex92** [BG-Software-LLC/SSB-OneBlock#1]
How do I add it to the server? where do I download it? or do I have to compile it myself? and where do I put the JAR file? in the plugins folder or inside SSB folder?

**Comment by joex92** [comment]
It seems that it only compiles for 1.12 and below... but not for 1.13+, and I need for 1.16.5... How!? what do I do to compile it for 1.16.5????

**Comment by joex92** [comment]
I supposely compiled it as the readme file said... but I get this error on boot:
```
[10:14:32 INFO]: [SSBOneBlock] Loading SSBOneBlock v1.1.0
[10:14:32 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing SSBOneBlock v1.1.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.bgsoftware.ssboneblock.OneBlockPlugin.log(OneBlockPlugin.java:99) ~[?:?]
        at com.bgsoftware.ssboneblock.OneBlockPlugin.loadNMSAdapter(OneBlockPlugin.java:67) ~[?:?]
        at com.bgsoftware.ssboneblock.OneBlockPlugin.onLoad(OneBlockPlugin.java:28) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Airplane-2]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-2]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by OmerBenGera** [comment]
> I supposely compiled it as the readme file said... but I get this error on boot:
> 
> ```
> [10:14:32 INFO]: [SSBOneBlock] Loading SSBOneBlock v1.1.0
> [10:14:32 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing SSBOneBlock v1.1.0 (Is it up to date?)
> java.lang.NullPointerException: null
>         at com.bgsoftware.ssboneblock.OneBlockPlugin.log(OneBlockPlugin.java:99) ~[?:?]
>         at com.bgsoftware.ssboneblock.OneBlockPlugin.loadNMSAdapter(OneBlockPlugin.java:67) ~[?:?]
>         at com.bgsoftware.ssboneblock.OneBlockPlugin.onLoad(OneBlockPlugin.java:28) ~[?:?]
>         at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Airplane-2]
>         at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Airplane-2]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Airplane-2]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-2]
>         at java.lang.Thread.run(Thread.java:834) [?:?]
> ```

Send me the entire logs, I will check it out
