### ISSUE TITLE
Invalid adapter for version v1_8_R3

### ISSUE THREAD

**Issue by Jackiedk100** [BG-Software-LLC/SSB-OneBlock#4]
Hello,
I get this error, when trying to use SSB-OneBlock on my server.
`[12:54:30] [Server thread/INFO]: [SSBOneBlock] Loading SSBOneBlock v1.1.0
[12:54:30] [Server thread/INFO]: [SSBOneBlock] Invalid adapter for version v1_8_R3
[12:54:30] [Server thread/ERROR]: null initializing SSBOneBlock v1.1.0 (Is it up to date?)
java.lang.NullPointerException
	at com.bgsoftware.ssboneblock.OneBlockPlugin.onLoad(OneBlockPlugin.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:302) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:218) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:615) [GemSpigot.jar:git-TacoSpigot-fd3209f3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

What do you think the cause is to this?

**Comment by Jackiedk100** [comment]
Also happening with latest version of spigot 1.8.8
```
[12:25:34] [Server thread/INFO]: [SSBOneBlock] Loading SSBOneBlock v1.1.0

[12:25:34] [Server thread/INFO]: [SSBOneBlock] Invalid adapter for version v1_8_R3

[12:25:34] [Server thread/ERROR]: null initializing SSBOneBlock v1.1.0 (Is it up to date?)

java.lang.NullPointerException

	at com.bgsoftware.ssboneblock.OneBlockPlugin.onLoad(OneBlockPlugin.java:31) ~[?:?]

	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
