### ISSUE TITLE
Error when Loading oneblock (Latest version) Also stops server

### ISSUE THREAD

**Issue by DeactDev** [BG-Software-LLC/SSB-OneBlock#46]
### Minecraft's Version

Minecraft 1.19.2 Running latest Pufferfish jar

### Plugin's Version

1.2.1 b36 Latest Dev Build

### Describe the bug

When loading the module it displays this error and stops the server after it loads with no error

`[23:29:09] [Server thread/INFO]: [SuperiorSkyblock2] Enabling the module OneBlock...
[23:29:09] [Server thread/WARN]: java.lang.NoSuchMethodError: 'boolean com.bgsoftware.common.mappings.MappingsChecker.checkMappings(java.lang.String, java.lang.String)'
[23:29:09] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.OneBlockModule.loadNMSAdapter(OneBlockModule.java:118)
[23:29:09] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.OneBlockModule.onEnable(OneBlockModule.java:48)
[23:29:09] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b788.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:122)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[23:29:09] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[23:29:09] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b788.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:166)
[23:29:09] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b788.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:513)
[23:29:09] [Server thread/WARN]: 	at SuperiorSkyblock2-1.11.1-b788.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:255)
[23:29:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:29:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[23:29:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[23:29:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[23:29:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[23:29:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[23:29:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[23:29:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[23:29:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1128)
[23:29:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[23:29:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

### To Reproduce

Load the module

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
