### ISSUE TITLE
SuperiorSkyblock2 One-Block Addon 

### ISSUE THREAD

**Issue by Huslyx1** [BG-Software-LLC/SSB-OneBlock#48]
### Minecraft's Version

Minecraft Version: 1.8.8
Server Version: 1.8.8

### Plugin's Version

SuperiorSkyblock2 v1.7.0-DEVb167

### Describe the bug

```
[01:33:35] [Server thread/INFO]: [0;33;1m[SuperiorSkyblock2] [0;33;1mFinished enabling the module missions (Took 114ms)[m
[01:33:35] [Server thread/INFO]: [0;32;1m[SuperiorSkyblock2] [0;32;1mEnabling the module OneBlock...[m
[01:33:35] [Server thread/WARN]: java.lang.NoSuchMethodError: 'void com.bgsoftware.ssboneblock.OneBlockModule.saveResource(java.lang.String)'
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.handler.SettingsHandler.<init>(SettingsHandler.java:30)
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.OneBlockModule.onReload(OneBlockModule.java:80)
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.ssboneblock.OneBlockModule.onEnable(OneBlockModule.java:50)
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.handlers.ModulesHandler.enableModule(ModulesHandler.java:92)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[01:33:35] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.handlers.ModulesHandler.enableModules(ModulesHandler.java:123)
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:422)
[01:33:35] [Server thread/WARN]: 	at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:193)
[01:33:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[01:33:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[01:33:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[01:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[01:33:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[01:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:403)
[01:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:367)
[01:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:322)
[01:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:283)
[01:33:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:558)
[01:33:35] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

Having an issue with One-Block addon

### To Reproduce

Download v1.7.0-DEVb167 and place it in the server, then place Module One-block into modules and bam.

**Comment by OmerBenGera** [comment]
Update SSB. You use a version that is more than a year outdated.
