### ISSUE TITLE
Latest OneBlock won't start in 1.19.3

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#52]
### Minecraft's Version

1.19.3 paper-1.19.3-334

### Plugin's Version

SuperiorSkyblock2-2022.9-b930
SSBOneBlock-1.2.1-b46

### Describe the bug

[16:18:44 INFO]: [SuperiorSkyblock2] Enabling the module OneBlock...
[16:18:44 INFO]: [SuperiorSkyblock2-OneBlock] Data version: 3218
[16:18:44 INFO]: [SuperiorSkyblock2-OneBlock] The plugin doesn't support your minecraft version.
[16:18:44 INFO]: [SuperiorSkyblock2-OneBlock] Please try a different version.
[16:18:44 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while disabling the module OneBlock.
[16:18:44 ERROR]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.
[16:18:44 WARN]: java.lang.RuntimeException: Couldn't find a valid nms support for your version.
[16:18:44 WARN]:        at com.bgsoftware.ssboneblock.OneBlockModule.onEnable(OneBlockModule.java:54)
[16:18:44 WARN]:        at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModule(ModulesManagerImpl.java:120)
[16:18:44 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[16:18:44 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[16:18:44 WARN]:        at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
[16:18:44 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[16:18:44 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[16:18:44 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[16:18:44 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[16:18:44 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:18:44 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[16:18:44 WARN]:        at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.module.ModulesManagerImpl.enableModules(ModulesManagerImpl.java:159)
[16:18:44 WARN]:        at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:525)
[16:18:44 WARN]:        at SuperiorSkyblock2-2022.9-b930.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:255)
[16:18:44 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:18:44 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[16:18:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[16:18:44 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[16:18:44 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[16:18:44 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[16:18:44 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[16:18:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[16:18:44 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[16:18:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[16:18:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

Use the same version and start the server

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
