### ISSUE TITLE
When a coop member mine the last block of a phase, it becomes bedrock

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SSB-OneBlock#61]
### Minecraft's Version

paper-1.19.3-397

### Plugin's Version

SSBOneBlock-1.2.1-b56
SuperiorSkyblock2-2022.9-b972

### Describe the bug

When a coop member breaks the last block of the last phase, it becomes a bedrock and an admin has to come manually /oneblock setphase player 1
Is there something that can fix this so coop member can break the oneblock in the last block/phases? 
[03:50:26 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2022.9-b969 generated an exception while executing task 62624614
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/SuperiorSkyblock2/modules/SSBOneBlock-1.2.1-b55.jar
        at com.bgsoftware.superiorskyblock.api.modules.ModuleResources.getResource(ModuleResources.java:86) ~[SuperiorSkyblock2-2022.9-b969.jar:?]
        at com.bgsoftware.superiorskyblock.api.modules.PluginModule.getResource(PluginModule.java:231) ~[SuperiorSkyblock2-2022.9-b969.jar:?]
        at com.bgsoftware.ssboneblock.handler.SettingsHandler.<init>(SettingsHandler.java:41) ~[?:?]
        at com.bgsoftware.ssboneblock.OneBlockModule.onReload(OneBlockModule.java:79) ~[?:?]
        at com.bgsoftware.ssboneblock.commands.commands.CmdReload.lambda$perform$0(CmdReload.java:49) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-388]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

When a coop member breaks the last block of the last phase, it becomes a bedrock and an admin has to come manually /oneblock setphase player 1
Is there something that can fix this so coop member can break the oneblock in the last block/phases? 

I dont know if this is linked to it
[03:50:26 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v2022.9-b969 generated an exception while executing task 62624614
java.lang.IllegalArgumentException: The embedded resource 'config.yml' cannot be found in plugins/SuperiorSkyblock2/modules/SSBOneBlock-1.2.1-b55.jar
        at com.bgsoftware.superiorskyblock.api.modules.ModuleResources.getResource(ModuleResources.java:86) ~[SuperiorSkyblock2-2022.9-b969.jar:?]
        at com.bgsoftware.superiorskyblock.api.modules.PluginModule.getResource(PluginModule.java:231) ~[SuperiorSkyblock2-2022.9-b969.jar:?]
        at com.bgsoftware.ssboneblock.handler.SettingsHandler.<init>(SettingsHandler.java:41) ~[?:?]
        at com.bgsoftware.ssboneblock.OneBlockModule.onReload(OneBlockModule.java:79) ~[?:?]
        at com.bgsoftware.ssboneblock.commands.commands.CmdReload.lambda$perform$0(CmdReload.java:49) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-388]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
I don't know why the module can't find the config file, however don't reload it.
Instead, unload and load the module using `/is admin module` and the bug should not occur.

**Comment by iSeitan** [comment]
Im sorry i dont understand? How is this not a bug and how can i prevent this from happening :)?

**Comment by OmerBenGera** [comment]
> Im sorry i dont understand? How is this not a bug and how can i prevent this from happening :)?

Do not use the reload command of the module itself and instead unload and load it which should fix everything.

**Comment by iSeitan** [comment]
My issue is not with "how to fix this"
I would like a way to prevent this alltogheter
A lot of people play with other player as coop, why would the oneblock become a bedrock everytime.
I cant just go manually fix this everytime

**Comment by mrtiny** [comment]
I'm from the iSeitan's server and the mainly one bothered by this issue.

I recorded the problem to better understand what is happening.

https://youtu.be/1FKrJ4BPMO8

do you have any bypass or fix for this inconvenience ?

**Comment by OmerBenGera** [comment]
I can't replicate the issue
any player that break the block will cause the same effect - the next phase will start.
I suspect the issue occurs because of the reload command and not breaking the one block as coop.
Try restarting the server without running reload command, check if it still occurs

**Comment by iSeitan** [comment]
Yes normally the OneBlock would indicate the end of the phase then change to a new phase but it doesn’t, it stays a bedrock

In this video we don’t do any command, the player is coop, and the bedrock stays like that for hours unti we reload the module

**Comment by OmerBenGera** [comment]
> Yes normally the OneBlock would indicate the end of the phase then change to a new phase but it doesn’t, it stays a bedrock
> 
> In this video we don’t do any command, the player is coop, and the bedrock stays like that for hours unti we reload the module

I cannot replicate the issue myself.
Try replicating it on a server with only SSB installed as well as the module.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
