### ISSUE TITLE
Symbols error and "grass" item inexistent

### ISSUE THREAD

**Issue by DextralityNetwork** [BG-Software-LLC/SSB-OneBlock#77]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/65f62f3b-3cf0-4af6-b087-f64f13b0a7bc)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/6fdacd1d-2dec-4052-b922-5897a9a6c7a8)

### Describe the bug

Symbols are not displayed:
![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/cd74f973-ff7b-4c16-aa79-7e4552117d22)
![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/c2e07a11-0d26-4e0a-adca-fcba779239b6)

Also i dont have "Grass" item in oneblock but send me in config this:
![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/33b32217-d7ae-4a01-9504-bc095d96a13e)

### To Reproduce

only break items

### Additional Information

https://media.discordapp.net/attachments/1000093530221457539/1206845870201503764/image.png?ex=65dd7dcd&is=65cb08cd&hm=14c74a5640dcedbc43cfabb3f33c89bbc8b1159e729f0bb8ab2b6437422418e0&=&format=webp&quality=lossless&width=1208&height=288

**Comment by OmerBenGera** [comment]
grass should be GRASS_BLOCK
Regarding the utf-8 chars, are you sure titles can even support these?

**Comment by DextralityNetwork** [comment]
> grass should be GRASS_BLOCK Regarding the utf-8 chars, I will look into that

If u can see in this line
"Picos de hielo.json"

https://paste.helpch.at/xivafinaza.json

i dont have any grass item

![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/bbd52c5d-85f9-4a7b-9341-8a61c607111d)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by DextralityNetwork** [comment]
![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/a5c524c6-39da-40fb-b5cd-b029c7466151)
Problem persist last ss version and last ss oneblock addon version

**Comment by DextralityNetwork** [comment]
Also right know phases in superior oneblock are broken :)

[22:24:16 INFO]: GeRmAnAnToNiO issued server command: /oneblock setphaseblock SLAY3R77 1
[22:24:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'oneblock setphaseblock SLAY3R77 1' in com.bgsoftware.ssboneblock.commands.CommandsHandler(oneblock)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2217) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2177) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1462) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1439) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1362) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1340) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 31 out of bounds for length 31
        at com.bgsoftware.ssboneblock.handler.PhasesHandler.setPhaseBlock(PhasesHandler.java:129) ~[?:?]
        at com.bgsoftware.ssboneblock.commands.commands.CmdSetPhaseBlock.perform(CmdSetPhaseBlock.java:72) ~[?:?]
        at com.bgsoftware.ssboneblock.commands.CommandsHandler.execute(CommandsHandler.java:49) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 28 more

**Comment by DextralityNetwork** [comment]
The BlockableEventLoop dont works

**Comment by OmerBenGera** [comment]
> ![image](https://private-user-images.githubusercontent.com/99357255/305672913-a5c524c6-39da-40fb-b5cd-b029c7466151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2OTU3ODUsIm5iZiI6MTcwODY5NTQ4NSwicGF0aCI6Ii85OTM1NzI1NS8zMDU2NzI5MTMtYTVjNTI0YzYtMzlkYS00MGZiLWI1Y2QtYjAyOWM3NDY2MTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEzMzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MzlkYjkzYzViNDZmZmYwZWJhY2M5ZGMwZDE2MDg5NjAwZjdhNWNiM2NjZDM3YmJhNjBlNDI4YTI3NGRlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDMGtOHwreEem6dU8WgFKDh2AcFlchuGgjcR8f5O4e4) Problem persist last ss version and last ss oneblock addon version

You need to replace `grass` with `grass_block`, as I already told you.
They changed the name of the grass block in 1.20.4

**Comment by DextralityNetwork** [comment]
i say again i dont have any item like name "grass"

**Comment by DextralityNetwork** [comment]
https://paste.helpch.at/yiqoyenuve.json

**Comment by OmerBenGera** [comment]
> i say again i dont have any item like name "grass"

There is a place where you have "grass".
Find it and replace it.

Closing this for now.

**Comment by DextralityNetwork** [comment]
Please read the file, I don't have anything called "grass".

**Comment by DextralityNetwork** [comment]
see this log sabana.json 
https://paste.helpch.at/yiqoyenuve.json

**Comment by DextralityNetwork** [comment]
![image](https://github.com/BG-Software-LLC/SSB-OneBlock/assets/99357255/8471be6e-47a0-4095-9374-1dfbfa160a21)

**Comment by OmerBenGera** [comment]
Whqt about savana-blocks, or any other file that ia mentioned in there?

**Comment by Yaosanqi137** [comment]
dude , I also have same issue in my server , and i can't find any 'grass' in my file , did you find out  the way to solve this problem?
