### ISSUE TITLE
Error one block is not working

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SSB-OneBlock#8]
[07:17:03 INFO]: [SuperiorSkyblock2] An error occurred while enabling the module OneBlock:
[07:17:03 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "org.bukkit.plugin.java.JavaPlugin.getCommand(String)" is null
[07:17:03 WARN]:        at com.bgsoftware.ssboneblock.OneBlockModule.onEnable(OneBlockModule.java:47)
[07:17:03 WARN]:        at SuperiorSkyblock2-1.8.4.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModule(ModulesHandler.java:106)
[07:17:03 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[07:17:03 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[07:17:03 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[07:17:03 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[07:17:03 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[07:17:03 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[07:17:03 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[07:17:03 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[07:17:03 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[07:17:03 WARN]:        at SuperiorSkyblock2-1.8.4.jar//com.bgsoftware.superiorskyblock.module.ModulesHandler.enableModules(ModulesHandler.java:140)
[07:17:03 WARN]:        at SuperiorSkyblock2-1.8.4.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:460)
[07:17:03 WARN]:        at SuperiorSkyblock2-1.8.4.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[07:17:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:17:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:17:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[07:17:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[07:17:03 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[07:17:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
[07:17:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
[07:17:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
[07:17:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
[07:17:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[07:17:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:17:03 INFO]: [SuperiorSkyblock2] Contact Ome_R regarding this, this has nothing to do with the plugin.

**Comment by OmerBenGera** [comment]
Use latest version of the addon.
