### ISSUE TITLE
Dosn't run

### ISSUE THREAD

**Issue by Coreli0** [BG-Software-LLC/SSB-OneBlock#86]
### Minecraft's Version

1.20.6

### Plugin's Version

2024.1 stable

### Describe the bug

[22:37:12 ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins\.paper-remapped\SSBOneBlock-2024.1.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins\.paper-remapped\SSBOneBlock-2024.1.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:81) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins\.paper-remapped\SSBOneBlock-2024.1.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        ... 9 more

### To Reproduce

run server

**Comment by S4LPICON** [comment]
Can you verify that you have the "plugin.yml" file? I think that error is about that file
`name: SSBOneBlock
version: 1.0
main: com.yourbussines.yourplugin.Main
api-version: 1.20
description: A description for you plugin.
author: YourName
`

**Comment by Coreli0** [comment]
I don't have this file.  What I need to do?

**Comment by S4LPICON** [comment]
It goes in the "resources" folder, you put "plugin.yml" with the information just like what happened before, you just need to have the main class in the path and that's it, you compile it and that's it, I would do it but I don't know how to make a pull request xd

**Comment by Coreli0** [comment]
what I need to do?

**Comment by OmerBenGera** [comment]
This is a module to SSB, not a standalone plugin.
Move it to the modules folder under SuperiorSkyblock's plugin folder
